# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler

# metadata:
#   name: apache-hpa
#   namespace: apache

# spec:
#   scaleTargetRef:  # Reference to the target Deployment to be autoscaled
#     apiVersion: apps/v1
#     kind: Deployment
#     name: apache-deploy

#   minReplicas: 1
#   maxReplicas: 5

#   metrics:   # Metric type to base scaling on
#   - type: Resource    
#     resource:
#       name: cpu      # Resource to monitor
#       target:
#         type: Utilization    # Target type
#         averageUtilization: 5



apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: apache-hpa
  namespace: apache

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deploy

  minReplicas: 1
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

  