apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: apache

spec:
  scaleTargetRef:            
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deploy

  minReplicas: 1
  maxReplicas: 5

  metrics:
  - type: Resource           # CPU metric
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

  - type: Resource           # Memory metric
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
