apiVersion: apps/v1
kind: Deployment

# Deplyoment Metadata - consists namespace and name of deploymnet
metadata:
  name: nginx-deploy
  namespace: nginx

# Deployment specs - consists an replicas and selector to match labels of pod 
spec:  
  replicas: 2
  selector:
    matchLabels:               
      app: nginx  #this should be same as labels under template

  #Pod template
  template:    
    metadata:
      name: nginx-deploy-pod
      labels:     # Deployment creates pods by taking these labels as reference           
        app: nginx

    #Pod spec
    spec:
      containers:
      - name: nginx-deploy-cont
        image: nginx:latest
        ports:
        - containerPort: 80
