apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
spec:
  clusterIP: None                 # Headless Service (REQUIRED for StatefulSet)
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sset
  namespace: mysql
spec:
  serviceName: mysql-svc          # REQUIRED
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "chintan1234"
        - name: MYSQL_DATABASE
          value: "devops"
        - name: MYSQL_USER
          value: "chintan"
        - name: MYSQL_PASSWORD
          value: "chintan1234"

        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
