apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mysql-vpa
  namespace: mysql
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mysql-sset

  updatePolicy:
    updateMode: "Auto"   # Only recommendations, NO eviction

  # resourcePolicy:
  #   containerPolicies:
  #   - containerName: mysql-cont
  #     controlledResources: ["cpu", "memory"]
  #     minAllowed:
  #       cpu: "200m"
  #       memory: "256Mi"
  #     maxAllowed:
  #       cpu: "2"
  #       memory: "4Gi"

