
#Volume Creation using Persistent Volume out of Host machine directory

apiVersion: v1
kind: PersistentVolume

metadata:
  name: hostvolume2
  labels:
    type: local #Optional

#Volume spec  
spec:
  storageClassName: local-storage  
  persistentVolumeReclaimPolicy: Retain  #Means even if PVC is deleted data will be there
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data    #path on the host machine even if its not there it will get created
    type: DirectoryOrCreate


---
#Persistent Volume Claim Creation
# This one just enough when we mount an external storage like ebs to k8s cluster no need to write pv.yml as pv automatically gets created when we create pvc with the help of storage class in pvc
# 
#but here we are creating pvc for host path pv created above

apiVersion: v1
kind: hostVolume2claim

metadata:
  name: hostvolume2claim
  labels:
    type: local
  namespace: storagek8s

# PVC spec       
spec:
  storageClassName: local-storage #Should be same as PV
  accessModes:
    - ReadWriteOnce  #Should be same as PV
  resources:
    requests:
      storage: 500Mi  #Should be less than or equal to PV size
